general.import = ["~/.config/alacritty/colors.toml"]

[font]
size = 16

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
opacity = 1

[window.padding]
x = 15
y = 15

[window.dimensions]
columns = 150
lines = 100

[env]
TERM = "xterm-256color"
